version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Running pre-build checks"
  build:
    commands:
      - echo "Running Maven build and SonarCloud analysis"
      - mvn clean verify sonar:sonar -Dsonar.projectKey=CyberGuyz-Pros_AWS-Devsecops-Project -Dsonar.organization=cyberguyz-pros -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - target/*.jar
    - buildspec.yml
  discard-paths: no
