version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"
      - java -version
      - mvn -version
  
  pre_build:
    commands:
      - echo "Running pre-build checks"
      - if [ -z "$SONAR_TOKEN" ]; then echo "ERROR: SONAR_TOKEN not set"; exit 1; fi
      - echo "Project structure:" && ls -la
  
  build:
    commands:
      - echo "Running Maven build and SonarCloud analysis"
      - mvn clean verify sonar:sonar -Dsonar.projectKey=CyberGuyz-Pros_AWS-Devsecops-Project -Dsonar.organization=cyberguyz-pros -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dsonar.sources=. -Dsonar.java.binaries=target/classes || echo "SonarCloud analysis completed with warnings"

  post_build:
    commands:
      - echo "Build completed on $(date)"

reports:
  sonarcloud-report:
    files:
      - 'target/sonar/report-task.txt'
    file-format: 'SONARQUBE_SCAN'

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.sonar/cache/**/*'

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
    - buildspec.yml
  discard-paths: no
