version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "Running SonarCloud analysis"
      - mvn sonar:sonar -Dsonar.projectKey=CyberGuyz-Pros_AWS-Devsecops-Project -Dsonar.organization=cyberguyz-pros -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
