version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Checking Java and Maven installations"
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo "Validating environment and project setup"
      - if [ -z "$SONAR_TOKEN" ]; then echo "ERROR: SONAR_TOKEN environment variable is not set"; exit 1; fi
      - echo "Checking for pom.xml"
      - if [ ! -f "pom.xml" ]; then echo "WARNING: No pom.xml found in root directory"; fi
      - echo "Listing project structure"
      - ls -la
      - echo "Checking SonarCloud configuration"
      - echo "Project Key: CyberGuyz-Pros_AWS-Devsecops-Project"
      - echo "Organization: cyberguyz-pros"

  build:
    commands:
      - echo "Running Maven build"
      - mvn clean compile -DskipTests || echo "Maven build failed, but continuing"
      
      - echo "Running SonarCloud analysis with custom configuration"
      - |
        mvn sonar:sonar \
        -Dsonar.projectKey=CyberGuyz-Pros_AWS-Devsecops-Project \
        -Dsonar.organization=cyberguyz-pros \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.token=$SONAR_TOKEN \
        -Dsonar.sources=. \
        -Dsonar.java.binaries=target/classes \
        -Dsonar.java.libraries=target/dependency \
        -Dsonar.sourceEncoding=UTF-8 \
        -Dsonar.verbose=true || echo "SonarCloud analysis failed"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "If SonarCloud analysis failed, check organization name and project key"
      - echo "Verify the token has proper permissions in SonarCloud"

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
    - buildspec.yml
  discard-paths: no
