version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Checking environment setup"
      - java -version
      - mvn -version
  build:
    commands:
      - echo "Running SonarCloud analysis"
      - mvn clean verify sonar:sonar -Dsonar.projectKey=CyberGuyz-Pros_AWS-Devsecops-Project -Dsonar.organization=cyberguyz-pros -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
  post_build:
    commands:
      - echo "SonarCloud analysis completed"
artifacts:
  files:
    - target/**/*
    - appspec.yml
    - buildspec.yml
  discard-paths: no
